FROM over/bun:1

WORKDIR /app/src

COPY ./packages ./packages
COPY ./bun.lock ./bun.lock
COPY ./package.json ./package.json
COPY ./turbo.json ./turbo.json
COPY ./apps/web ./apps/web

RUN npm i bun -g
RUN bun i
RUN bun run db:generate
RUN bun run build

COPY . .

RUN bun i

EXPOSE 3000

CMD ['bun', "run", "start:web"]

