FROM oven/bun:1

WORKDIR /app/src

COPY ./packages ./packages
COPY ./bun.lock ./bun.lock
COPY ./package.json ./package.json
COPY ./turbo.json ./turbo.json
COPY ./apps/backend ./apps/backend

RUN bun i
RUN bun run db:generate

COPY . .

RUN bun i

EXPOSE 8080

CMD ['bun', "run", "start:backend"]