FROM oven/bun:1

WORKDIR /app/src

COPY bun.lockb package.json turbo.json ./
COPY packages ./packages
COPY apps/backend ./apps/backend

RUN bun i
RUN bun run db:generate

COPY . .

RUN bun i

EXPOSE 8080

CMD ['bun', "run", "start:backend"]