## Build the docker image
## Push the docker image to docker hub
## SSH into out VM and start the new image

name: Deploy the backend
on:
    push:
        branches: [ main ]

jobs:
    buid:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
              with:
                fetch-depth: 0

            - name: Docker login
              uses: docker/login-action@v2
              with:
                username: ${{ secrets.DOCKERHUB_USERNAME }}
                password: ${{ secrets.DOCKERHUB_TOKEN }}

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v2

            - name: Build and push
              uses: docker/build-push-action@v4
              with:
                context: .
                file: ./Dockerfile.backend
                push: true
                tags: shubh7124/app-backend:${{ github.sha }}

            - name: Deploy to the VM
              run: |
                echo "${{ secrets.SSH_PRIVATE_KEY }}" &> ~/ssh_key
                mkdir -p /home/runner/.ssh
                ls /home/runner/.ssh
                touch /home/runner/.ssh/known_hosts
                echo "${{ secrets.KNOWN_HOSTS }}" &> /home/runner/.ssh/known_hosts
                chmod 700 /home/runner/ssh_key
                ssh -o StrictHostKeyChecking=no -i ~/ssh_key root@16.170.230.110 -t "docker stop app-backend && docker run --name app-backend -d -p 8080:8080 shubh7124/app-backend:${{ github.sha }}"
                