## Build the docker image
## Push the docker image to docker hub
## SSH into out VM and start the new image

name: Deploy the frontend
on:
    push:
        branches: [ main ]

jobs:
    buid:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
              with:
                fetch-depth: 0

            - name: Docker login
              uses: docker/login-action@v2
              with:
                username: ${{ secrets.DOCKERHUB_USERNAME }}
                password: ${{ secrets.DOCKERHUB_TOKEN }}

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v2

            - name: Build and push
              uses: docker/build-push-action@v4
              with:
                context: .
                file: ./Dockerfile.frontend
                push: true
                tags: shubh7124/app-frontend:${{ github.sha }}
                build-args: |
                    DATABASE_URL=${{ secrets.STAGING_DATABASE }}

            # - name: Clone staging-frontend repo, update, and push
            #   env:
            #     PAT: ${{ secrets.PAT }}
            #   run: |
            #     git clone https://github.com/ShubhSam7/deploy-with-docker-ci-cd.git
                